//! The shared half of the P-code record, `tests/pcode.toml`.
//!
//! Two binaries compile this file with `#[path]`: the gate test
//! `crates/deform6/tests/pcode_record.rs`, and `crates/xtask`, whose
//! `import-pcode` writes the record. Nothing in this file is a test. It uses
//! the shared half of the build record, which each of the two binaries holds
//! as the module `build_record` at its root.

use std::collections::BTreeMap;
use std::path::{Path, PathBuf};

use sha2::{Digest, Sha256};

use crate::build_record::{
    Outcome, is_files_hash, messages, only_fields, outcome, quoted, render_messages, table, text,
};

/// The comment block above the first table. A constant, so a rewrite never
/// copies it from the old file.
pub(crate) const HEADER: &str = r"# The committed P-code record: what the Visual Basic 6 IDE built as P-code
# for each corpus program, on a Windows host.
#
# Do not edit this file by hand. To rewrite it:
#   1. cargo run -p xtask -- export-pcode <dir>
#   2. On the Windows host, run build.bat in <dir>, then sendpcode.bat.
#   3. cargo run -p xtask -- import-pcode --capture <file> <dir>
# `cargo test -p deform6 --test pcode_record` holds the tree to this file.
#
# `environment` holds the Windows version and the line for VB6.EXE that
# build.bat wrote on the host, and the line that the export wrote into each
# project file in place of `CompilationType=0`.
#
# A `program` table describes one corpus program. Its key is the path of the
# native executable, relative to `corpus/`. `source` is the hash of the files
# of the corpus project that VB6 reads, before the one line changed. `result`
# is `built`, `built with load errors`, `failed` or `not run`. For a program
# that built, `exe` is the SHA-256 of the executable, which is at the same
# path under `corpus-pcode/`. The messages are the lines that VB6 wrote, with
# each path cut to start at the project directory.
#
# When the source of a program changes, `source` does not match, and the gate
# fails until the host builds the program again.
";

/// The record of one corpus program.
#[derive(Clone, Debug, PartialEq, Eq)]
pub(crate) struct PcodeBuild {
    /// The [`crate::build_record::files_hash`] of the files of the corpus
    /// project, from [`crate::build_record::source_files`].
    pub(crate) source: String,
    /// What the host did with the project.
    pub(crate) result: Outcome,
    /// The [`exe_hash`] of the executable, for a program that built. `None`
    /// for any other result.
    pub(crate) exe: Option<String>,
    /// The lines that VB6 wrote, for a program that did not build cleanly.
    pub(crate) messages: Vec<String>,
}

/// The whole record.
#[derive(Clone, Debug, Default, PartialEq, Eq)]
pub(crate) struct PcodeRecord {
    /// The Windows version that `ver` gave on the host.
    pub(crate) windows: String,
    /// The line for `VB6.EXE` that `dir` gave on the host.
    pub(crate) vb6: String,
    /// The line that the export wrote in place of `CompilationType=0`.
    pub(crate) compilation_type: String,
    /// One entry for each corpus program, by key.
    pub(crate) programs: BTreeMap<String, PcodeBuild>,
}

/// Gives the path of the committed record.
pub(crate) fn pcode_toml_path() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("../../tests/pcode.toml")
}

/// Gives the directory that holds the committed P-code executables.
pub(crate) fn pcode_root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("../../corpus-pcode")
}

/// Gives the SHA-256 of the bytes of one file, as `sha256:` and 64 lower
/// case hexadecimal characters.
pub(crate) fn exe_hash(bytes: &[u8]) -> String {
    let digest: String = Sha256::digest(bytes)
        .iter()
        .map(|byte| format!("{byte:02x}"))
        .collect();
    format!("sha256:{digest}")
}

/// Renders one program table.
pub(crate) fn render_program(key: &str, program: &PcodeBuild) -> String {
    let mut out = format!("[program.{}]\n", quoted(key));
    out.push_str(&format!("source = {}\n", quoted(&program.source)));
    out.push_str(&format!("result = {}\n", quoted(program.result.word())));
    if let Some(exe) = &program.exe {
        out.push_str(&format!("exe = {}\n", quoted(exe)));
    }
    out.push_str(&render_messages("messages", &program.messages));
    out
}

/// Renders the whole file: [`HEADER`], then `environment`, then every
/// program in key order. One blank line comes before each table, and the
/// file ends with one newline.
pub(crate) fn render(record: &PcodeRecord) -> String {
    let mut out = String::from(HEADER);
    out.push_str(&format!(
        "\n[environment]\nwindows = {}\nvb6 = {}\ncompilation_type = {}\n",
        quoted(&record.windows),
        quoted(&record.vb6),
        quoted(&record.compilation_type)
    ));
    for (key, program) in &record.programs {
        out.push('\n');
        out.push_str(&render_program(key, program));
    }
    out
}

fn parse_program(key: &str, value: &toml::Value) -> Result<PcodeBuild, String> {
    let what = format!("program.{key:?}");
    let program = table(value, &what)?;
    only_fields(program, &["source", "result"], &["exe", "messages"], &what)?;
    let source = text(program, "source", &what)?;
    if !is_files_hash(source) {
        return Err(format!(
            "{what}.source = {source:?} is not sha256: and 64 lower case hexadecimal characters"
        ));
    }
    let result = outcome(program, "result", &what)?;
    let exe = match program.get("exe") {
        Some(_) => {
            let exe = text(program, "exe", &what)?;
            if !is_files_hash(exe) {
                return Err(format!(
                    "{what}.exe = {exe:?} is not sha256: and 64 lower case hexadecimal characters"
                ));
            }
            Some(exe.to_owned())
        }
        None => None,
    };
    if exe.is_some() != (result == Outcome::Built) {
        return Err(format!(
            "{what} is {}, and an exe goes with a program that built, and only with one",
            result.word()
        ));
    }
    let messages = messages(program, "messages", &what)?;
    if result == Outcome::Built && !messages.is_empty() {
        return Err(format!("{what} built, and holds messages"));
    }
    Ok(PcodeBuild {
        source: source.to_owned(),
        result,
        exe,
        messages,
    })
}

/// Reads the text of a record.
pub(crate) fn parse(text_of_file: &str) -> Result<PcodeRecord, String> {
    let root: toml::Table = text_of_file
        .parse()
        .map_err(|err| format!("tests/pcode.toml is not valid TOML: {err}"))?;
    only_fields(&root, &["environment", "program"], &[], "tests/pcode.toml")?;

    let environment = table(
        root.get("environment")
            .ok_or("tests/pcode.toml has no environment")?,
        "environment",
    )?;
    only_fields(
        environment,
        &["windows", "vb6", "compilation_type"],
        &[],
        "environment",
    )?;
    let mut record = PcodeRecord {
        windows: text(environment, "windows", "environment")?.to_owned(),
        vb6: text(environment, "vb6", "environment")?.to_owned(),
        compilation_type: text(environment, "compilation_type", "environment")?.to_owned(),
        programs: BTreeMap::new(),
    };
    let programs = table(
        root.get("program")
            .ok_or("tests/pcode.toml has no program")?,
        "program",
    )?;
    for (key, value) in programs {
        record
            .programs
            .insert(key.clone(), parse_program(key, value)?);
    }
    Ok(record)
}
