#![allow(
    clippy::unwrap_used,
    clippy::expect_used,
    clippy::panic,
    clippy::indexing_slicing,
    clippy::arithmetic_side_effects,
    clippy::integer_division,
    reason = "the test harness, embedded in two binaries: it reads a vendored corpus this \
              repository controls, and it reports a fault in this repository loudly"
)]

//! The shared half of the committed build record, `tests/builds.toml`.
//!
//! Two binaries compile this file. `crates/deform6/tests/build_record.rs` is
//! the gate, and `crates/xtask` is the exporter and the writer (`cargo run -p
//! xtask -- export-builds` and `import-builds`). Both take the files, the
//! hash, the text and the parser from here, so the gate and the writer cannot
//! disagree about which files a build covers or about the shape of the
//! record.
//!
//! This file sits in a directory that Cargo does not build as a test target.
//! It holds no test of its own, so nothing here runs twice.
//!
//! # Why the record holds a hash
//!
//! A result in the record is true only for the files that the Windows host
//! built. [`files_hash`] names those files. The gate writes the files again
//! with [`project_files`] and compares the two hashes, so a change to the
//! files that DeForm6 writes fails the gate until the host builds the new
//! files.
//!
//! # The text is written by hand, and read by the `toml` crate
//!
//! [`render`] builds the text with `format!`. [`parse`] reads it with
//! `toml::Table`. The two are independent, so a render fault that makes text
//! the parser reads in a different way shows as a difference.

use std::collections::BTreeMap;
use std::path::{Path, PathBuf};

use deform6::journal::Mode;
use deform6::vb::opcodes::OpcodeTable;
use sha2::{Digest, Sha256};

/// The number of executables the corpus vendors.
pub(crate) const EXPECTED_PROGRAM_COUNT: usize = 44;

/// The extensions of the files that the Visual Basic 6 IDE reads when it
/// builds a project: the project file, the forms and their resources, the
/// modules and the classes. The JSON report is not one of them.
pub(crate) const BUILD_EXTENSIONS: &[&str] = &["vbp", "frm", "frx", "bas", "cls"];

/// The comment block above the first table. A constant, so a rewrite never
/// copies it from the old file.
pub(crate) const HEADER: &str = r"# The committed build record: what the Visual Basic 6 IDE built for each
# corpus program, on a Windows host.
#
# Do not edit this file by hand. To rewrite it:
#   1. cargo run -p xtask -- export-builds <dir>
#   2. On the Windows host, run build.bat in <dir>.
#   3. cargo run -p xtask -- import-builds <dir>
# `cargo test -p deform6 --test build_record` holds the tree to this file.
#
# `environment` holds the Windows version and the line for VB6.EXE that
# build.bat wrote on the host.
#
# A `program` table describes one corpus program. Its key is the path of the
# executable, relative to `corpus/`. `files` is the hash of the files that
# DeForm6 wrote for the program and that the host built. `original` is the
# result for the project in the corpus, and `extracted` is the result for the
# project that DeForm6 wrote. A result is `built`, `failed` or `not run`. The
# messages are the lines that VB6 wrote, with each path cut to start at the
# project directory.
#
# When DeForm6 writes different files for a program, `files` does not match,
# and the gate fails until the host builds the new files.
";

/// What the host did with one project.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub(crate) enum Outcome {
    /// VB6 built the project.
    Built,
    /// VB6 did not build the project.
    Failed,
    /// The host has no result for the project.
    NotRun,
}

impl Outcome {
    /// The word that the record holds for this outcome.
    pub(crate) const fn word(self) -> &'static str {
        match self {
            Self::Built => "built",
            Self::Failed => "failed",
            Self::NotRun => "not run",
        }
    }

    /// Reads a word of the record.
    pub(crate) fn from_word(word: &str) -> Option<Self> {
        [Self::Built, Self::Failed, Self::NotRun]
            .into_iter()
            .find(|outcome| outcome.word() == word)
    }
}

/// The result for one project of a program: the project in the corpus, or
/// the project that DeForm6 wrote.
#[derive(Clone, Debug, PartialEq, Eq)]
pub(crate) struct Side {
    pub(crate) outcome: Outcome,
    /// The lines that VB6 wrote for this project.
    pub(crate) messages: Vec<String>,
}

/// The record of one corpus program.
#[derive(Clone, Debug, PartialEq, Eq)]
pub(crate) struct ProgramBuild {
    /// The [`files_hash`] of the files that the host built.
    pub(crate) files: String,
    pub(crate) original: Side,
    pub(crate) extracted: Side,
}

/// The whole record.
#[derive(Clone, Debug, Default, PartialEq, Eq)]
pub(crate) struct BuildRecord {
    /// The Windows version that `ver` gave on the host.
    pub(crate) windows: String,
    /// The line that `dir` gave for `VB6.EXE` on the host.
    pub(crate) vb6: String,
    /// The programs, by key.
    pub(crate) programs: BTreeMap<String, ProgramBuild>,
}

/// Gives the path of the committed record.
pub(crate) fn builds_toml_path() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("../../tests/builds.toml")
}

/// Gives the directory that holds the `corpus/` this workspace vendors.
pub(crate) fn corpus_root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("../../corpus")
}

/// Gives every `.exe` under `root`, compared case-insensitively, sorted.
///
/// Skips each directory named `fetched`. The fetched programs have no
/// licence that permits a committed file derived from them, so the record
/// must never hold one.
pub(crate) fn executables(root: &Path) -> Result<Vec<PathBuf>, String> {
    let mut out = Vec::new();
    collect(root, &mut out)?;
    out.sort();
    Ok(out)
}

fn collect(dir: &Path, out: &mut Vec<PathBuf>) -> Result<(), String> {
    let entries =
        std::fs::read_dir(dir).map_err(|err| format!("reading {}: {err}", dir.display()))?;
    for entry in entries {
        let path = entry
            .map_err(|err| format!("reading an entry of {}: {err}", dir.display()))?
            .path();
        if path.is_dir() {
            if path.file_name().is_some_and(|name| name == "fetched") {
                continue;
            }
            collect(&path, out)?;
        } else if path
            .extension()
            .is_some_and(|ext| ext.eq_ignore_ascii_case("exe"))
        {
            out.push(path);
        }
    }
    Ok(())
}

/// Gives a program's key: its path relative to `root`, joined with `/` on
/// every host.
pub(crate) fn program_key(exe: &Path, root: &Path) -> Result<String, String> {
    let relative = exe
        .strip_prefix(root)
        .map_err(|err| format!("{} is not under {}: {err}", exe.display(), root.display()))?;
    Ok(relative
        .components()
        .map(|part| part.as_os_str().to_string_lossy().into_owned())
        .collect::<Vec<_>>()
        .join("/"))
}

/// Keeps the files whose extension is in [`BUILD_EXTENSIONS`], compared
/// case-insensitively, in the order they come.
pub(crate) fn build_files(files: Vec<(String, Vec<u8>)>) -> Vec<(String, Vec<u8>)> {
    files
        .into_iter()
        .filter(|(name, _bytes)| {
            Path::new(name).extension().is_some_and(|ext| {
                BUILD_EXTENSIONS
                    .iter()
                    .any(|known| ext.eq_ignore_ascii_case(known))
            })
        })
        .collect()
}

/// Gives the files that DeForm6 writes for the executable `exe_bytes`, and
/// that the Visual Basic 6 IDE reads: the files of a strict run of `inspect`
/// and `write::project` with the built-in opcode table, through
/// [`build_files`]. The exporter and the gate both call this, so they build
/// the same files.
pub(crate) fn project_files(exe_bytes: &[u8]) -> Result<Vec<(String, Vec<u8>)>, String> {
    let table = OpcodeTable::builtin();
    let report = deform6::inspect(exe_bytes, &table, Mode::Strict)
        .map_err(|err| format!("inspect: {err}"))?;
    let written = deform6::write::project(&report, exe_bytes, Mode::Strict)
        .map_err(|err| format!("write::project: {err}"))?;
    Ok(build_files(
        written
            .files
            .into_iter()
            .map(|file| (file.name, file.bytes))
            .collect(),
    ))
}

/// Gives the hash of a set of files, as `sha256:` and 64 lower case
/// hexadecimal characters.
///
/// The files are taken in the order of their names. For each file, the hash
/// takes the bytes of the name, one `0x00` byte, the length of the file as a
/// `u64` in little-endian order, and the bytes of the file. The length keeps
/// the boundary between two files: without it, one file could hold the name
/// and the bytes of the next one, and give the same hash.
pub(crate) fn files_hash(files: &[(String, Vec<u8>)]) -> String {
    let mut sorted: Vec<&(String, Vec<u8>)> = files.iter().collect();
    sorted.sort_by(|a, b| a.0.cmp(&b.0));
    let mut hasher = Sha256::new();
    for (name, bytes) in sorted {
        hasher.update(name.as_bytes());
        hasher.update([0_u8]);
        let len = u64::try_from(bytes.len()).expect("a file length fits a u64");
        hasher.update(len.to_le_bytes());
        hasher.update(bytes);
    }
    let digest: String = hasher
        .finalize()
        .iter()
        .map(|byte| format!("{byte:02x}"))
        .collect();
    format!("sha256:{digest}")
}

fn quoted(text: &str) -> String {
    toml::Value::String(text.to_owned()).to_string()
}

fn render_messages(field: &str, messages: &[String]) -> String {
    if messages.is_empty() {
        return String::new();
    }
    let mut out = format!("{field} = [\n");
    for message in messages {
        out.push_str(&format!("  {},\n", quoted(message)));
    }
    out.push_str("]\n");
    out
}

/// Renders one program table.
pub(crate) fn render_program(key: &str, program: &ProgramBuild) -> String {
    let mut out = format!("[program.{}]\n", quoted(key));
    out.push_str(&format!("files = {}\n", quoted(&program.files)));
    out.push_str(&format!(
        "original = {}\n",
        quoted(program.original.outcome.word())
    ));
    out.push_str(&format!(
        "extracted = {}\n",
        quoted(program.extracted.outcome.word())
    ));
    out.push_str(&render_messages(
        "original_messages",
        &program.original.messages,
    ));
    out.push_str(&render_messages(
        "extracted_messages",
        &program.extracted.messages,
    ));
    out
}

/// Renders the whole file: [`HEADER`], then `environment`, then every
/// program in key order. One blank line comes before each table, and the
/// file ends with one newline.
pub(crate) fn render(record: &BuildRecord) -> String {
    let mut out = String::from(HEADER);
    out.push_str(&format!(
        "\n[environment]\nwindows = {}\nvb6 = {}\n",
        quoted(&record.windows),
        quoted(&record.vb6)
    ));
    for (key, program) in &record.programs {
        out.push('\n');
        out.push_str(&render_program(key, program));
    }
    out
}

fn table<'a>(value: &'a toml::Value, what: &str) -> Result<&'a toml::Table, String> {
    value
        .as_table()
        .ok_or_else(|| format!("{what} is not a table"))
}

fn text<'a>(table: &'a toml::Table, field: &str, what: &str) -> Result<&'a str, String> {
    table
        .get(field)
        .ok_or_else(|| format!("{what} has no {field}"))?
        .as_str()
        .ok_or_else(|| format!("{what}.{field} is not a string"))
}

fn only_fields(
    table: &toml::Table,
    required: &[&str],
    optional: &[&str],
    what: &str,
) -> Result<(), String> {
    for key in table.keys() {
        if !required.contains(&key.as_str()) && !optional.contains(&key.as_str()) {
            return Err(format!("{what} has an unknown entry {key:?}"));
        }
    }
    for field in required {
        if !table.contains_key(*field) {
            return Err(format!("{what} has no {field}"));
        }
    }
    Ok(())
}

fn outcome(table: &toml::Table, field: &str, what: &str) -> Result<Outcome, String> {
    let word = text(table, field, what)?;
    Outcome::from_word(word).ok_or_else(|| {
        format!("{what}.{field} = {word:?} is not one of \"built\", \"failed\" and \"not run\"")
    })
}

fn messages(table: &toml::Table, field: &str, what: &str) -> Result<Vec<String>, String> {
    let Some(value) = table.get(field) else {
        return Ok(Vec::new());
    };
    let array = value
        .as_array()
        .ok_or_else(|| format!("{what}.{field} is not an array"))?;
    array
        .iter()
        .map(|line| {
            line.as_str()
                .map(str::to_owned)
                .ok_or_else(|| format!("{what}.{field} holds a value that is not a string"))
        })
        .collect()
}

/// True when `value` is `sha256:` and 64 lower case hexadecimal characters.
fn is_files_hash(value: &str) -> bool {
    value.strip_prefix("sha256:").is_some_and(|hex| {
        hex.len() == 64
            && hex
                .bytes()
                .all(|byte| byte.is_ascii_digit() || (b'a'..=b'f').contains(&byte))
    })
}

fn parse_program(key: &str, value: &toml::Value) -> Result<ProgramBuild, String> {
    let what = format!("program.{key:?}");
    let program = table(value, &what)?;
    only_fields(
        program,
        &["files", "original", "extracted"],
        &["original_messages", "extracted_messages"],
        &what,
    )?;
    let files = text(program, "files", &what)?;
    if !is_files_hash(files) {
        return Err(format!(
            "{what}.files = {files:?} is not sha256: and 64 lower case hexadecimal characters"
        ));
    }
    Ok(ProgramBuild {
        files: files.to_owned(),
        original: Side {
            outcome: outcome(program, "original", &what)?,
            messages: messages(program, "original_messages", &what)?,
        },
        extracted: Side {
            outcome: outcome(program, "extracted", &what)?,
            messages: messages(program, "extracted_messages", &what)?,
        },
    })
}

/// Reads the text of a record.
pub(crate) fn parse(text_of_file: &str) -> Result<BuildRecord, String> {
    let root: toml::Table = text_of_file
        .parse()
        .map_err(|err| format!("tests/builds.toml is not valid TOML: {err}"))?;
    only_fields(&root, &["environment", "program"], &[], "tests/builds.toml")?;

    let environment = table(&root["environment"], "environment")?;
    only_fields(environment, &["windows", "vb6"], &[], "environment")?;
    let mut record = BuildRecord {
        windows: text(environment, "windows", "environment")?.to_owned(),
        vb6: text(environment, "vb6", "environment")?.to_owned(),
        programs: BTreeMap::new(),
    };
    for (key, value) in table(&root["program"], "program")? {
        record
            .programs
            .insert(key.clone(), parse_program(key, value)?);
    }
    Ok(record)
}
